### ISSUE TITLE
fatal: Not a valid object name origin/main

### ISSUE THREAD

**Issue by macosgrove** [fcsonline/rubocop-changes#12]
We have a buildkite step that uses rubocop-changes v0.8.1 to fail the build if Rubocop violations are present in edited code. We have recently switched our repo from "master" to "main". We are now seeing this error:

`fatal: Not a valid object name origin/main`

We have tried all these commands:

```
bundle exec rubocop-changes
bundle exec rubocop-changes -b main
RUBOCOP_CHANGES_BASE_BRANCH=main bundle exec rubocop-changes
```
All have the same result.

**Comment by fcsonline** [comment]
Review that you are checking out both branches, there current one and main one. If you are using GitHub actions, double check the parameters of checkout action.

Let me know if this.

**Comment by fcsonline** [comment]
Closing issue.
