### ISSUE TITLE
Getting "Not a valid object name origin/main" error while using rubocop-changes versions '0.6.0' / '0.7.0'

### ISSUE THREAD

**Issue by Anusalini** [fcsonline/rubocop-changes#8]
Ruby version: 2.5.1p57
Bundle version: 1.17.3

**It's working fine when we use version '0.5.0'**

Logs:
fatal: Not a valid object name origin/main
Traceback (most recent call last):
	from  ~/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:22:in `<main>'
        from ~/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:22:in `eval'
        from ~/.rvm/gems/ruby-2.5.1/bin/rubocop-changes:23:in `<main>'
	from ~/.rvm/gems/ruby-2.5.1/bin/rubocop-changes:23:in `load'
	from ~/.rvm/gems/ruby-2.5.1/gems/rubocop-changes-0.7.0/exe/rubocop-changes:17:in `<top (required)>'
~/.rvm/gems/ruby-2.5.1/gems/rubocop-changes-0.7.0/lib/rubocop/changes/checker.rb:27:in `run': Rubocop::Changes::UnknownForkPointError (Rubocop::Changes::UnknownForkPointError)

**Comment by fcsonline** [comment]
You should pass which is your base branch in your repository with the `-b` argument. By default is `main` but for many repositories used to be `master`. If your usually have the same base branch, you can set `RUBOCOP_CHANGES_BASE_BRANCH` environment variable too.

**Comment by Anusalini** [comment]
It worked on passing -b arg. Thanks much @fcsonline! As I have mentioned above, it doesn't require -b arg for version 0.5.0. It's working even without -b. If this is because of new versions, can you please update the same in the readme?

**Comment by fcsonline** [comment]
> It worked on passing -b arg. Thanks much @fcsonline! As I have mentioned above, it doesn't require -b arg for version 0.5.0. It's working even without -b. If this is because of new versions, can you please update the same in the readme?

Yep, this is because we were assuming `master` as base branch. 

I'll update the documentation.

**Comment by fcsonline** [comment]
https://github.com/fcsonline/rubocop-changes/commit/f7621484a1d25a3b0fbef87fb8cdba870d613918
